android.useAndroidX=true
android.newDsl=false
android.defaults.buildfeatures.buildconfig=true
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseSerialGC
systemProp.android.newDsl=false
kotlin.incremental=false
org.gradle.workers.max=1
org.gradle.daemon=false
android.enableR8.fullMode=false
